// Generated by Copilot
// Jest test for API connectivity
const fetch = require('node-fetch');

describe('API Connectivity', () => {
  const API_URL = 'http://localhost:8081/api/tasks';

  it('should confirm API is available', async () => {
    const response = await fetch(API_URL, {
      method: 'HEAD',
      headers: { 'Content-Type': 'application/json' }
    });
    expect(response.ok).toBe(true);
  });

  it('should GET tasks', async () => {
    const response = await fetch(API_URL);
    expect(response.ok).toBe(true);
    const tasks = await response.json();
    expect(Array.isArray(tasks)).toBe(true);
  });

  it('should POST and DELETE a task', async () => {
    const testTaskTitle = 'Test task ' + new Date().toISOString();
    const postTask = await fetch(API_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ title: testTaskTitle })
    });
    expect(postTask.ok).toBe(true);
    const newTask = await postTask.json();
    expect(newTask).toHaveProperty('id');

    // Delete the created task
    const deleteTask = await fetch(`${API_URL}/${newTask.id}`, {
      method: 'DELETE'
    });
    expect(deleteTask.ok).toBe(true);
  });
});
